### ISSUE TITLE
Pn tu nombre completo aqui

### ISSUE THREAD

**Issue by lasr21** [gitcommituyu/grupo2_2023#1]
agrega tu completo completo para el cerficcado

**Comment by BashkitoShengo** [comment]
Dennis Ferreyra Casaman

**Comment by difortunamateo** [comment]
Mateo Di Fortuna

**Comment by Antoneleca** [comment]
Antonella Herrera

**Comment by RafaelEsc** [comment]
Santiago Rafael Escobar Ayala

**Comment by Santiago1Gonzalez** [comment]
Santiago Gonzalez Carrasco

**Comment by SantiAmaro** [comment]
Santiago Amaro

**Comment by GastonVenturelli** [comment]
Gastón Venturelli Rivero

**Comment by RosaLucas12** [comment]
Lucas Rosa

**Comment by CarvalloRocio** [comment]
Rocío Carvallo

**Comment by FrancoMartinez2005** [comment]
Franco Martínez Camaño

**Comment by lherrera37** [comment]
Lucas Herrera

**Comment by RodriguezT11** [comment]
Amir Aarón Rodríguez Techera

**Comment by AdanMarino** [comment]
Adan Marino

**Comment by KiaraC82** [comment]
Kiara Crossa

**Comment by yasmimSoutoo** [comment]
Yasmim Souto Gindri

**Comment by BDMaggio** [comment]
Bruno Jesus Di Maggio Olivera

**Comment by Lmontiel08** [comment]
Lautaro Ezequiel Montiel Casanova

**Comment by AgustinBrum** [comment]
Agustin Nicolas Brum Gracia

**Comment by LuisIVP** [comment]
Luis Vázquez

**Comment by Alexis-Mendez14** [comment]
Alexis Mendez Alzogaray

**Comment by LopezJhoel** [comment]
Jhoel López

**Comment by ZaZaA77** [comment]
Zayanna Pinochet

**Comment by Frankiitoo** [comment]
Franco Tomas Oviedo Segovia

**Comment by lusmila1311** [comment]
Lusmila Belén Rodríguez Trinidad

**Comment by Benjamin-Chain** [comment]
Benjamin Ignacio Chain Maldonado

**Comment by facundo-pineyrua** [comment]
Facundo Piñeyrúa

**Comment by AntonellaDiaz12** [comment]
Jenniffer Antonella Diaz Bell

**Comment by luzmilarojas** [comment]
Luzmila sharon rojas barboza

**Comment by TomasSuares** [comment]
Tomas Suárez Rodríguez

**Comment by BrunoSilva999** [comment]
Bruno Gustavo Silva Moreno

**Comment by lherrera37** [comment]
Lucas Ezequiel Herrera Salvotelli

**Comment by leosilva12** [comment]
Leonardo Leonel Silva Lemos

**Comment by SantiAmaro** [comment]
Santiago Gaston Amaro Luz

**Comment by SuarezHD** [comment]
Matias Suarez Machado

**Comment by VicoAlmeida** [comment]
Victoria Avril Almeida Morales

**Comment by luzmilarojas** [comment]
Luzmila Sharon rojas barboza

**Comment by KatyyGS** [comment]
Katherine González Segura

**Comment by AlejoSantos08** [comment]
Alejo Daniel Santos Alcoba.
